# Site Configuration

# Theme, mapped to the directory: ./theme/xxxx
theme: default

# HTML Language setting
lang: "en"

# Plugins, implemented in ./plugins/PLUGIN_NAME
# Use {{ vars.PLUGIN_NAME }} in the settings below

# The output of the plugin can be used below, e.g., {{vars.MediumFollowersCountPlugin}}
plugins:
  # Automatically fetch Medium follower count
  - MediumFollowersCountPlugin:
      username: zhgchgli
  # Automatically fetch Github repo star count
  - GithubRepoStarsCountPlugin:
      - ZhgChgLi/ZMarkupParser
      - ZhgChgLi/ZReviewTender
      - ZhgChgLi/ZMediumToMarkdown
      - ZhgChgLi/linkyee

# Google Analytics tracking id
google_analytics_id:

# HTML Title
title: "Zhanglq Links"

# Avatar image path
avatar: "./images/profile.jpeg"

# Name section text
name: "@ZHANGLQ"

# Tagline section text
tagline: >-
    A Software Engineer.

# List of links
# icon: Use Font Awesome icons (https://fontawesome.com/search?o=r&m=free)
# text: The displayed text for the link
# title: The url title
# url: The URL of the link
# alt: Alternative text for accessibility
# target: `_blank` opens in a new tab, `_self` opens in the same frame
links:
  - link:
      icon: "fa-brands fa-google-scholar"
      text: "Google Scholar"
      url: "https://scholar.google.com/citations?user=DZ31t2IAAAAJ"
      alt: "Zhanglq's Google Scholar"
      title: "Zhanglq's Google Scholar"
      target: "_blank"
  - link:
      icon: "fa-brands fa-github"
      text: "Github"
      url: "https://github.com/zhanglq2024"
      alt: "Zhanglq's Github"
      title: "Zhanglq's Github"
      target: "_blank"
  - link:
      icon: "fa-solid fa-code"
      text: "Leetcode"
      url: "https://leetcode.com/u/carpdm/"
      alt: "Zhanglq's Leetcode"
      title: "Zhanglq's Leetcode"
      target: "_blank"
  - link:
      icon: "fa-brands fa-twitter"
      text: "X (Twitter)"
      url: "https://x.com/cpdm0330"
      alt: "Zhanglq's X"
      title: "Zhanglq's X"
      target: "_blank"


socials:  
  - social:  
      icon: "fa-brands fa-medium"  
      url: "https://blog.zhgchg.li"  
      title: "ZhgChgLi 的 Medium"  
      alt: "ZhgChgLi 的 Medium"  
      target: "_blank"  
  - social:  
      icon: "fa-brands fa-github"  
      url: "https://github.com/ZhgChgLi"  
      title: "ZhgChgLi 的 GitHub"  
      alt: "ZhgChgLi 的 GitHub"  
      target: "_blank"  
  - social:  
      icon: "fa-brands fa-twitter"  
      url: "https://twitter.com/zhgchgli"  
      title: "ZhgChgLi 的 Twitter"  
      alt: "ZhgChgLi 的 Twitter"  
      target: "_blank"  
  - social:  
      icon: "fa-brands fa-linkedin"  
      url: "https://www.linkedin.com/in/zhgchgli/"  
      title: "ZhgChgLi 的 LinkedIn"  
      alt: "ZhgChgLi 的 LinkedIn"  
      target: "_blank"  
  - social:  
      icon: "fa-brands fa-instagram"  
      url: "https://www.instagram.com/zhgchgli/"  
      title: "Instagram"  
      alt: "ZhgChgLi 的 Instagram"  
      target: "_blank"  
  - social:  
      icon: "fa-solid fa-envelope"  
      url: "zhgchgli@gmail.com"  
      title: "Email: zhgchgli@gmail.com"  
      alt: "zhgchgli@gmail.com"  
      target: "_blank"  

# Footer text
footer: >
    Hi there! Follow me on Medium or GitHub, or stay connected on Instagram or LinkedIn.

# Footer copyright message
# Linkyee is a 100% free, open-source project—feel free to modify the copyright message as you like. :)
copyright: >
  © 2024  <a href="https://zhgchg.li" target="_blank">ZhgChgLi</a>. Powered by <a href="https://github.com/ZhgChgLi/linkyee" target="_blank">linkyee</a>
